name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main  # Exécute la pipeline sur chaque push dans la branche `main`

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Vérifiez le code source
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configure Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Backend
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      run: |
        docker build -t jalalhamdane/qr-code-backend:latest ./backend
        docker push jalalhamdane/qr-code-backend:latest

    # Construire et pousser le frontend
    - name: Build and Push Frontend
      run: |
        docker build -t jalalhamdane/qr-code-frontend:latest ./frontend
        docker push jalalhamdane/qr-code-frontend:latest
